In [ ]:
# import the libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

### Start working on a real dataset

We're going to use the House Price dataset we used last time ([link text](https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data?select=train.csv))

Try to upload the dataset on your Google Drive and access it through Colab.

In [ ]:
# find the file on your system and copy and paste the path here
FILE_PATH = "/content/train.csv"
df = ...

In [ ]:
# show all the columns
pd.set_option('display.max_columns', None)

In [ ]:
# print the shape of the dataset


In [ ]:
# check the data types


In [ ]:
# take a look at the first few records


In [ ]:
# take a look at the columns


In [ ]:
# look at the correlation of columns with .corr()

# plot the correlations with sns.heatmap


In [ ]:
# run the code bellow to have a better view of corrolations
def plot_corr_matrix(df, nr_c, targ) :
    """
    A function for getting the features with the highest
    corrolation with the target variable.
    """

    # get the values
    corr = df.corr()
    corr_abs = corr.abs()

    # get the names in the largest to smallest order
    cols = corr_abs.nlargest(nr_c, targ)[targ].index
    cm = np.corrcoef(df[cols].values.T)

    # plot the figure
    plt.figure(figsize=(nr_c/1.5, nr_c/1.5))
    sns.set(font_scale=1.25)
    sns.heatmap(cm, linewidths=1.5, annot=True, square=True,
                fmt='.2f', annot_kws={'size': 10},
                yticklabels=cols.values, xticklabels=cols.values)
    print('The highest corrolations are with the following columns:\n', cols)
    plt.show()

plot_corr_matrix(df, nr_c=5, targ='SalePrice')

In [ ]:
# copy the list of columns printed out on the output of previous code cell
# and paste it here
columns_to_use =

# filter the above columns of the dataset and save the new dataset into df_sample
df_sample = ...

In [ ]:
# look into the number of nulls we have in df_sample


In [ ]:
# take a look at the sampled dataset


In [ ]:
# plot GrLivArea against SalePrice with a scatter plot


In [ ]:
# Delete the outliers (ones that have GrLivArea more than 4000)
df_sample = ...

# plot it again


In [ ]:
# create a variable called X_columns and put all the column names
# (except for your target column name) in it
x_columns= ...

print(x_columns)

# filter df_sample based on the x_column_names and your target name
X = ...
y = ...

# build the train and test sets
X_train, X_test, y_train, y_test = ...

In [ ]:
# import the libraries for regression
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
# Initialize and train a linear regression model


# Make predictions


# Evaluate the model





In [ ]:
# Initialize and train a Ridge regression model


# Make predictions


# Evaluate the model




In [ ]:
# Initialize and train a Lasso regression model


# Make predictions


# Evaluate the model


In [ ]:
import matplotlib.pyplot as plt
col = 'GrLivArea'

plt.figure(figsize=(10, 6))

# Add a reference line for a perfect prediction (y_test = predictions)


# Create a scatter plot for Linear Regression


# Create a scatter plot for Ridge Regression


# Create a scatter plot for Lasso Regression



# Set plot labels and title


# Show the plot


* How are weights calculated: [link](https://towardsdatascience.com/step-by-step-tutorial-on-linear-regression-with-stochastic-gradient-descent-1d35b088a843)

* Why is Lasso harder on coefficients in comparison to Ridge? [link](https://online.stat.psu.edu/stat508/lesson/5/5.4)

* Regression requirements: [link](https://www.youtube.com/watch?v=0MFpOQRY0rw&ab_channel=zedstatistics)

* Linear regression in sklearn: [link](https://scikit-learn.org/stable/modules/linear_model.html#linear-models)

* Lasso Regression


### Add and convert categorical columns to numerical

In [ ]:
# filter the dataset based on the following columns
columns_to_use = ['LotArea', 'YrSold', 'GarageArea', 'GarageYrBlt',
                  'GrLivArea', 'OverallQual', 'ExterQual', 'YearBuilt',
                  'MSZoning', 'KitchenQual',
                  'SalePrice']

# save the new dataset into df_sample


In [ ]:
# take a look at the dataset


In [ ]:
# look into the number of nulls we have
# (sort the values to have the emptiest column on top)


In [ ]:
# fillna with mean for: GarageYrBlt


In [ ]:
# Check if nulls have been filled

In [ ]:
# import the label encoder
from sklearn.preprocessing import LabelEncoder

# create a second dataset from the first dataset
df_transformed = df_sample.copy()

# define the categorical columns
cols = ('KitchenQual', 'ExterQual', 'MSZoning')

# process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder()
    lbl.fit(list(df_transformed[c].values))
    df_transformed[c] = lbl.transform(list(df_transformed[c].values))



In [ ]:
# look at the transformed version
# is everything looking good?


In [ ]:
# Now let's go back to the original dataset "df_sample" by saving it in df_transformed to try another type of encoding


In [ ]:
# use ordinal encoder to transform kitchen quality (KitchenQual)
from sklearn.preprocessing import OrdinalEncoder

order = ['Fa','TA','Gd','Ex']
columns_with_order = ['ExterQual', 'KitchenQual']


In [ ]:
# take a look at the kitchQual in df_sample


In [ ]:
# take a look at the kitchQual in df_transformed


In [ ]:
# Specify the columns to be one-hot encoded (MSZoning)
# Perform one-hot encoding


# Concatenate the encoded columns with the original dataset


# Display the modified dataset


In [ ]:
# drop the columns you transformed and keep the converted versions
df_transformed.drop(columns=['MSZoning'], inplace=True)

In [ ]:
# define the variables we want to use for X (everything except for 'SalePrice')
X_columns = ...

# create X and y
X = ...
y = ...

# build the train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# View X_train. Is everything looking good?
X_train

In [ ]:
# Initialize and train a linear regression model


# Make predictions


# Evaluate the model


In [ ]:
# Initialize and train a Ridge regression model

# Make predictions


# Evaluate the model


In [ ]:
# Initialize and train a Lasso regression model


# Make predictions


# Evaluate the model



In [ ]:
import matplotlib.pyplot as plt
col = 'GrLivArea'

plt.figure(figsize=(10, 6))

# Add a reference line for a perfect prediction (y_test = predictions)


# Create a scatter plot for Linear Regression


# Create a scatter plot for Ridge Regression


# Create a scatter plot for Lasso Regression


# Set plot labels and title


# Show the plot



### Optional for now

### What if we didn't have normalized features?


In [ ]:
# Calculate the mean and standard deviation for each feature
mean = np.mean(X, axis=0)
std_dev = np.std(X, axis=0)

# Normalize the features using z-score standardization
X_normalized = (X - mean) / std_dev

# Now, X_normalized contains your normalized features
X_normalized

array([[-0.11880088,  1.30830738, -1.94596119, ..., -0.0799718 ,
         0.52392458, -0.2068604 ],
       [-0.74303607,  0.68323931, -0.04619011, ..., -0.41725697,
        -0.11423462, -0.12904578],
       [ 1.47897114, -0.81555906,  0.25820241, ..., -1.04435196,
        -0.46699142,  1.01243711],
       ...,
       [-0.30806122,  0.70698175, -0.10586411, ...,  2.57735983,
        -0.41305098,  0.86882684],
       [ 0.65574781,  0.677178  , -1.52848625, ..., -0.17924173,
         0.02779055, -2.05940375],
       [ 0.91263067, -0.54004781,  0.39728375, ...,  1.91455488,
        -1.85248203, -0.67698021]])

In [ ]:
#  other ways of doing this
from sklearn.preprocessing import StandardScaler

# Assuming you have a numpy array called 'X' containing your features
# X.shape should be (number_of_samples, number_of_features)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to your data and transform the features
X_normalized = scaler.fit_transform(X)

# X_normalized contains your z-score standardized features
X_normalized

array([[-0.11880088,  1.30830738, -1.94596119, ..., -0.0799718 ,
         0.52392458, -0.2068604 ],
       [-0.74303607,  0.68323931, -0.04619011, ..., -0.41725697,
        -0.11423462, -0.12904578],
       [ 1.47897114, -0.81555906,  0.25820241, ..., -1.04435196,
        -0.46699142,  1.01243711],
       ...,
       [-0.30806122,  0.70698175, -0.10586411, ...,  2.57735983,
        -0.41305098,  0.86882684],
       [ 0.65574781,  0.677178  , -1.52848625, ..., -0.17924173,
         0.02779055, -2.05940375],
       [ 0.91263067, -0.54004781,  0.39728375, ...,  1.91455488,
        -1.85248203, -0.67698021]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Assuming you have a numpy array called 'X' containing your features
# X.shape should be (number_of_samples, number_of_features)

# Create a MinMaxScaler instance (by default, scales to [0, 1])
scaler = MinMaxScaler()

# Fit the scaler to your data and transform the features
X_normalized = scaler.fit_transform(X)

# X_normalized contains your min-max scaled features
X_normalized

array([[0.53513317, 0.70448302, 0.19237754, ..., 0.45693682, 0.58597695,
        0.48918306],
       [0.4381887 , 0.60450883, 0.47924949, ..., 0.39572753, 0.47958645,
        0.50160903],
       [0.78326906, 0.3647891 , 0.52521381, ..., 0.28192459, 0.42077672,
        0.68388883],
       ...,
       [0.50574081, 0.60830623, 0.47023851, ..., 0.93917979, 0.42976938,
        0.66095616],
       [0.6554215 , 0.60353938, 0.25541769, ..., 0.43892167, 0.50326413,
        0.19335625],
       [0.69531571, 0.40885472, 0.54621557, ..., 0.81889634, 0.1897951 ,
        0.41411111]])